version: '3.9'

networks:
  api-network:
    driver: bridge
services:
  app:
    container_name: api_var1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - api-network
    depends_on:
      - db
    
  db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: var1
    volumes:
      - ./postgresql:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - api-network
volumes:
  postgresql: